using Library.DLL.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Library.DLL.EF
{
    /// <summary>
    /// Initializer of DB
    /// </summary>
    public class DBInitializer : DropCreateDatabaseAlways<LibraryContext>
    {
        /// <summary>
        /// Method for initializer
        /// </summary>
        /// <param name="context"></param>
        protected override void Seed(LibraryContext context)
        {
            context.Reviews.Add(new Review("Mark", "ITS really good site for reading and serching", DateTime.Now.AddDays(-1)));
            context.Reviews.Add(new Review("Kristina", "I found here a lot of interesting books, i advise it to you", DateTime.Now.AddDays(-3)));
            context.Reviews.Add(new Review("Danil", "the best site that i have found ever", DateTime.Now.AddDays(-4).AddHours(2)));
            context.Reviews.Add(new Review("Rustam", "So interesting site with a lot of interesting books and audiobooks", DateTime.Now.AddDays(-3).AddHours(-4)));

            context.Assays.Add(new Assay("Mark", "The left hand of darkness", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque, neque in varius euismod, mi est tincidunt enim, at bibendum est nunc vitae elit. In at aliquet elit. Vestibulum ultrices, nibh ac consequat laoreet, est odio ullamcorper nibh, eu eleifend mauris ante ac metus. Sed at purus pulvinar, vulputate est ac, feugiat diam. Phasellus ac pharetra augue. Aliquam erat volutpat. Nunc placerat, dolor in accumsan pulvinar, lorem augue convallis augue, at faucibus nisi metus ac sem. Duis id euismod purus, ut placerat purus.

Vivamus accumsan consequat suscipit. Aliquam finibus gravida sagittis. Suspendisse a nisi venenatis, eleifend magna sit amet, feugiat turpis. In eu consectetur massa, ac pretium nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec sed quam vel est pellentesque luctus. Vestibulum a justo ex. Pellentesque sit amet ipsum neque. Suspendisse vel finibus risus, a dignissim eros. Cras euismod sollicitudin ex, tempor tincidunt augue sagittis nec. Donec rutrum at nulla ut efficitur. Duis rutrum ornare imperdiet. Nam convallis nisi id arcu suscipit, ut tristique leo sagittis. Ut luctus eros quis pharetra aliquet. Sed eu scelerisque turpis, a rutrum purus.

Nullam vel venenatis eros. Maecenas porttitor pretium neque et sodales. Maecenas id sagittis lorem. Phasellus arcu massa, commodo non massa congue, consequat tincidunt felis.") { Tags = "Triller/Comedy" });
            context.Assays.Add(new Assay("Mark", "Wonder Woman : Steve Trevor", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
 { Tags = "Triller/Comedy" });
            context.Assays.Add(new Assay("Tom", "Batman : the caped crusader. Volume 4", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag1/Tag2" });
            context.Assays.Add(new Assay("Romert", "Miles Morales : great responsibility", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag2/Tag3" });
            context.Assays.Add(new Assay("Karson", " Wonder Woman : tempest tossed", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag2/Tag4" });
            context.Assays.Add(new Assay("Tom", "25 mujeres que dieron batalla", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag1/Tag3" });
            context.Assays.Add(new Assay("Makarov", "Secretos de chicas : una guía cool para entender tu cuerpo y sus cambios", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag2/Tag5" });
            context.Assays.Add(new Assay("Radchenko", "Por siempre jamás", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag1/Tag3" });
            context.Assays.Add(new Assay("Romert", "El hijo infinito", @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis lectus in ligula vehicula fringilla. Morbi ac facilisis nulla, a posuere ex. Donec et enim interdum, auctor tortor sit amet, imperdiet est. Maecenas nulla metus, fermentum a ipsum id, sagittis facilisis ante. Phasellus venenatis ullamcorper dapibus. Vivamus cursus quam congue massa interdum, vitae fermentum justo mattis. Aenean posuere mattis hendrerit.

Nulla ut lobortis enim, a convallis augue. Phasellus convallis, purus non posuere convallis, velit nisi ultricies eros, malesuada finibus leo mi sit amet enim. Fusce eu ornare libero. Phasellus imperdiet nec nisl vitae tempor. Integer a egestas diam. Sed at quam eu lorem tristique pretium. Maecenas dignissim bibendum lorem, quis sagittis odio laoreet id. Maecenas porta sem lectus, id ultrices turpis congue in. Vivamus sed fringilla dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Nulla tempor felis nec risus luctus, at ornare felis pharetra. Nullam iaculis nibh sed risus porta laoreet in ac elit. Curabitur id euismod urna, quis fermentum massa. Maecenas cursus magna sed orci imperdiet, sit amet dignissim nisi dictum. Vestibulum a eros a eros scelerisque lobortis quis non elit. Aliquam non bibendum leo. Fusce viverra mi sagittis velit vehicula congue. Etiam tristique ligula sit amet bibendum tincidunt. Nunc lobortis ex sed commodo molestie. Etiam sodales, dolor vel commodo finibus, leo arcu lacinia nibh, non suscipit metus lacus id ipsum. Proin congue tincidunt sollicitudin. Sed facilisis pretium purus, sit amet luctus elit volutpat vitae. Morbi in convallis.")
            { Tags = "Tag2/Tag5" });

            context.SaveChanges();
        }
    }
}
